
- package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-usb
    - python3-libusb1
    - python3-opencv
    - python3-numpy
    - python3-scipy
    - python3-matplotlib
    - python3-pil.imagetk
    - imagemagick
    - cmake
    - libboost-program-options-dev
    - libusb-dev
    - libusb-1.0-0-dev
    - libopencv-dev
    - linux-libc-dev  # needed for linux/limits.h in libseek build

- git:
    dest: /opt/libseek-thermal
    # upstream repo: https://github.com/OpenThermal/libseek-thermal
    repo: https://github.com/whacked/libseek-thermal
    version: temp-info_compact

- name: chown -R
  file:
    path: /opt/libseek-thermal
    recurse: yes
    owner: pi
    group: pi

- name: build libseek-thermal
  shell: "{{ item }}"
  args:
    chdir: /opt/libseek-thermal
  become: yes
  become_user: pi
  with_items:
    - mkdir -p build
    - cd build && cmake ..
    - cd build && make

- name: create udev rule for Seek Thermal Compact
  become: yes
  copy:
    dest: /etc/udev/rules.d/99-seekthermal.rules
    content: |
      SUBSYSTEM=="usb", ATTRS{idVendor}=="289d", ATTRS{idProduct}=="0010", MODE="0666", GROUP="users"

- name: reload udev rules
  become: yes
  shell: udevadm control --reload-rules && udevadm trigger
