---
- hosts: all
  connection: local
  vars:
      nix_init: '. ~/.nix-profile/etc/profile.d/nix.sh'
  tasks:

  - name: ensure apt cache is up to date
    apt: update_cache=yes
    become: true

  - name: ubuntu/vbox specific utils
    become: true
    package:
        name: "{{ item }}"
        state: latest
    with_items:
        - xfce4
        - xserver-xorg-legacy  # also for WM launch
        - virtualbox-guest-dkms
        - virtualbox-guest-utils
        - virtualbox-guest-x11
        - ttf-anonymous-pro
        - fonts-dejavu-core
        - fonts-dejavu-extra
        - ttf-bitstream-vera
        - fonts-inconsolata

  - name: fix for window manager launching with non-root
    become: true
    block:
    - lineinfile:
        # NOTE: as of 2.3 this should be `path`;
        # using `dest` because ubuntu is behind
        dest: /etc/X11/Xwrapper.config
        backup: yes
        regexp: '^allowed_users='
        line: 'allowed_users=anybody'
    - lineinfile:
        dest: /etc/X11/Xwrapper.config
        backup: yes
        state: present
        regexp: '^needs_root_rights='
        line: 'needs_root_rights=yes'

  - stat: path=/nix
    register: nixdir

  - name: install nix
    shell: curl https://nixos.org/nix/install | sh
    when: nixdir.stat.exists == False

  - name: update cabal
    shell: "{{ nix_init }}; cabal update"
  
  - name: use nix's cabal to install xmonad
    shell: |
        {{ nix_init }}
        nix-shell -p alsaLib pkgconfig xorg.libXext xorg.libXrandr xorg.libXinerama xorg.libXScrnSaver --run 'cabal install {{ item }}'
    with_items:
        - alex
        - happy
        - c2hs
        - xmonad
        - xmonad-contrib
        - xmonad-extras

  - name: install docker
    # see https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository
    become: true
    block:
    - package:
        name: "{{ item }}"
        state: latest
      with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
    - apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    - apt: update_cache=yes
      become: true
    - apt: pkg=docker-ce state=present
    - user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

  - name: post-install customization
    shell: "{{ nix_init }}; {{ item }}"
    with_items:
        - ln -sf $HOME/.nix-profile/share/oh-my-zsh $HOME/.oh-my-zsh
        - sudo usermod -s $(which zsh) $USER
        # ensure Emacs keys are loaded by default for gtk apps
        - mkdir -p ~/.themes
        - ln -sf $(find /nix/store -name gtk-keys.css | grep Emacs | head -1) ~/.themes/
        - mkdir -p ~/.xmonad
        - ln -sf ~/dot/xmonad.hs ~/.xmonad/
        - ln -sf ~/dot/Xmodmap ~/.Xmodmap

