- name: ensure apt cache is up to date
  apt: update_cache=yes

- package:
    name: "{{ item }}"
    state: latest
  with_items:
    - bluetooth
    - build-essential
    - cargo
    - clojure
    - default-jdk
    - emacs
    - gnuplot
    - golang
    - htop
    - jq
    - moreutils
    - nodejs
    - python-pexpect  # note on rpi3 this is python2
    - rustc
    - sqlite3
    - tcpdump
    - terminator
    - tmux
    - vim

- block:
  - shell: apt list ripgrep | grep ripgrep | wc -l
    register: rg_match
  
  - when: rg_match.stdout == "0"
    package:
      name: silversearcher-ag
      state: latest
  
  - when: rg_match.stdout != "0"
    package:
      name: ripgrep
      state: latest
  
# for 4GB RAM, ansible returns
# 3906, which is 4096*1024^2/1000^2;
# so 1GB is 1024*0.9765625^2 = 976
- when: ansible_memtotal_mb >= 976
  block:
  - group:
      name: docker
      state: present

  - user:
      name: pi
      groups: docker
      append: true

  - shell: command -v docker >/dev/null 2>&1
    register: check_docker_installed
    ignore_errors: true

  - shell: curl -sSL https://get.docker.com | sh
    when: check_docker_installed.rc == 1

