# see https://www.home-assistant.io/docs/installation/raspberry-pi/
- package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - libffi-dev
    - libssl-dev

- name: add HA manager user
  user:
    name: "{{ manager_user }}"
    comment: home assistant manager
    system: yes
    create_home: yes
    groups: dialout,gpio,i2c

- name: create installation directory
  file:
    path: "{{ install_directory }}"
    owner: "{{ manager_user }}"
    group: "{{ manager_user }}"
    state: directory

- block:
  
  - name: test
    shell: whoami
    args:
      chdir: "{{ install_directory }}"
  
  - name: create virtualenv
    shell: python3 -m venv venv
    args:
      chdir: "{{ install_directory }}"
  
  - name: virtualenv preflight install
    shell: source venv/bin/activate; python -m pip install wheel
    args:
      chdir: "{{ install_directory }}"
  
  - pip:
      name: ["homeassistant"]
      virtualenv: "{{ install_directory }}/venv"

  become: yes
  become_user: "{{ manager_user }}"

