- name: install nix package manager
  become: true
  become_user: "{{ admin_user }}"
    #ansible.builtin.shell: "sh <(curl -L https://nixos.org/nix/install) --daemon" executable=/bin/bash
  ansible.builtin.shell: sh <(curl -L https://nixos.org/nix/install) --no-daemon
  args:
    executable: /bin/bash

