- stat:
    path: "/opt/plantgateway"
  register: plantgateway

- when: plantgateway.stat.exists == False
  become: true
  become_user: pi
  block: 

  - git:
      repo: https://github.com/ChristianKuehnel/plantgateway
      dest: "/opt/plantgateway"
  
  - name: create venv
    shell: python3 -m venv venv
    args:
      chdir: "/opt/plantgateway"
  
  - name: install requirements
    shell: ./venv/bin/pip install -r requirements.txt
    args:
      chdir: "/opt/plantgateway"
  
  - name: add cron job for plantgateway exists for user pi
    ansible.builtin.cron:
      name: "Run plantgateway"
      user: "pi"
      job: "/bin/bash -c 'cd /home/pi/plantgateway && source ./venv/bin/activate && python plantgateway'"
      minute: "*/5"
      state: present
  
  - name: fix pip dependencies
    shell: ./venv/bin/pip install "{{ item }}"
    with_items:
    - typing-extensions  # needed for python <3.8
    - paho-mqtt==1.6.1   # fixes "Unsupported callback API version, from installing the default version == 2.0.0 as of this commit"
    args:
      chdir: "/opt/plantgateway"
  
