- stat:
    path: "{{ install_path }}"
  register: enviroplus

- file:
    path: "{{ build_path }}"
    owner: pi
    group: pi
    state: directory

- when: enviroplus.stat.exists == False
  become: yes
  become_user: pi
  block: 

  - git:
      repo: https://github.com/whacked/enviroplus-python
      dest: "{{ build_path }}"
  
  - shell: sudo FORCE='-y' ./install.sh
    args:
      chdir: "{{ build_path }}"

- name: copy getdata.py
  ansible.builtin.copy:
    src: files/getdata.py
    dest: "{{ getdata_path }}"
    owner: pi
    group: pi

- name: set up getdata.py crontab
  ansible.builtin.cron:
    name: "restart getdata"
    minute: "*"
    hour: "*/4"
    user: pi
    job: "cd /home/pi/Desktop; python {{ getdata_path }}"
