# ansible-playbook -i hosts $0
---
- hosts: raspberry-pi
  user: pi
  become: true
  roles:
  - grove-py
  - onewire
  - pimoroni
  - raspberry-pi-basic
  - rpi-co2meter
  - rpi-seek-thermal
  - temper
